import type { Metadata } from 'next';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

export const metadata: Metadata = {
    title: 'Erik Brandon Digital - About',
    description: 'Generated by create next app'
};

export default function About() {
    return (
        <>
            <main className='p-6 flex flex-1 justify-center items-center bg-cover bg-center bg-about-hero'>
                <h1 className='text-center text-6xl font-bold text-white'>
                    About Me
                </h1>
            </main>
        </>
    );
}
