import type { Metadata } from 'next';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

export const metadata: Metadata = {
    title: 'Erik Brandon Digital - Portfolio',
    description: 'Generated by create next app'
};

export default function Portfolio() {
    return (
        <>
            <main className='p-6 flex flex-1 justify-center items-center bg-cover bg-center bg-portfolio-hero'>
                <h1 className='text-center text-6xl font-bold text-white'>
                    Portfolio
                </h1>
            </main>
        </>
    );
}
